### ISSUE TITLE
Playlist "Finish Editing" rarely if ever works after adding songs

### ISSUE THREAD

**Issue by viscoci** [StarGazer1258/BeatDrop#23]
**Environment:**
OS - Windows 10
BeatDrop Version - 2.2.0

**Description of bug:**
Thanks for the great tools, I really appreciate the hard work put into Beat Drop.

*Problem:* While editing a playlist, the "Finish Editing" button rarely if ever works. Usually this occurs when a duplicate of a song appears.
Often, songs somehow appear as duplicates and one is usually not able to be removed.

**Steps to reproduce:**

1. Create a playlist
2. Notice that a song has duplicated itself
3. Attempt to fix,
4. Edit the playlist
5. Delete one of the duplicates (the available to remove one)
6. Attempt to finish editing by clicking finish editing button
7. Nothing happens
8. Close playlist and start a new one, hope that it doesn't happen again
9. Problem somehow gets worse, another duplicate that can't be deleted appears
10. Spend time making bug report because this happens a lot

**Expected behavior:**
Playlist updates with only one song and actually saves changes

**Actual Behavior**
Finish Editing button appears to do nothing when this bug occurs.
Another duplicate of the song may appear.

**Associated File**
[Week14YURWeeklyCommunityWorkout1558573589308.bplist as .txt](https://github.com/StarGazer1258/BeatDrop/files/3209966/Week14YURWeeklyCommunityWorkout1558573589308.txt)
**Screenshots:**
The song in question is Alone
![image](https://user-images.githubusercontent.com/37775195/58219780-1ba4a300-7cda-11e9-8572-a8f810f692f5.png)
![image](https://user-images.githubusercontent.com/37775195/58219798-28c19200-7cda-11e9-816a-672af37fc361.png)
![image](https://user-images.githubusercontent.com/37775195/58219809-35de8100-7cda-11e9-85fe-efd1e303379e.png)
![image](https://user-images.githubusercontent.com/37775195/58219818-3f67e900-7cda-11e9-9cb5-61ea2b0193fa.png)
![image](https://user-images.githubusercontent.com/37775195/58219833-4e4e9b80-7cda-11e9-8548-764a14863772.png)
![image](https://user-images.githubusercontent.com/37775195/58219853-573f6d00-7cda-11e9-9071-dfc374434a16.png)

**Comment by viscoci** [comment]
**Fix**
I have been removing the songs from the .bplist file manually. This usually works

**Comment by viscoci** [comment]
Also just noticed that I have this song downloaded and could be an older version than the one on beatsaver or possible the duplication may be caused by having the song downloaded prior to adding it to the playlist?

**Comment by xbkingx** [comment]
Same issue present in 2.5.5 beta. If an map folder has the old 1.5.0 and new 2.0.0 file versions, the playlist cannot be edited (tracks deleted or playlist renamed), unless an song with a clean (2.0.0 files only) is also deleted. No idea why these maps weren't fully converted, but they work in the game. These 1.5+2.0 folders have the old json and ogg extensions, in addition to the new dat and egg ones.

This didn't happen for just one track. I have hundreds of mixed tracks now, so this may be the root cause of some other problems. Ugh.

Tested by: 
1) Download a recent song (Song1) within BeatDrop. 
2) Add it to Playlist TestBD1. 
3) In song library, add a song that has the old 1.5 files in addition to the 2.0 files (Song2). 
4) Attempt to edit playlist name.
5) Click Finish editing - Nothing will happen.
6) Delete Song2 from playlist.
7) Click Finish editing - Nothing will happen.
8) Delete Song1 from playlist
9) Click Finish editing - Changes applied.

You can repeat with playlist with only Song1, or only Song2, or same as above, but deleting Song1 first (Song2 will be stuck in the playlist until you add a newly downloaded song to the playlist).
