### ISSUE TITLE
Right-Click context menu shows options for multiple other songs, but clicked one.

### ISSUE THREAD

**Issue by Drakonno** [StarGazer1258/BeatDrop#4]
**Environment:**
Device - PC 
OS - Windows 7, 6.1, 7601 SP1
BeatDrop Version - 2.1.6, Installation type - Steam, Song List has turned on Auto Load More

**Description of bug:**
After clicking with right mouse button on any of the custom songs available in my library, a random set of context windows with additional options are opened.

**Steps to reproduce:**

1. Open Beat Drop.
2. Go to "Library" select "Songs".
3. Right Click on any of the songs.

**Expected behavior:**
Context window with additional options (delete, add to playlist, share).
These options were earlier available just by hovering over the item on the list (that was also more convenient).

**Actual behavior:**
A group of context windows is opened, and none of them looks like for clicked element.

**Screenshots:**
![BeatDrop_Bug_001](https://user-images.githubusercontent.com/10178145/55906425-87bcc300-5bd4-11e9-95ab-7c71c13cdc56.jpg)

**Comment by Mace404** [comment]
I still have this with 2.18

**Comment by brandonhenry** [comment]
Having trouble reproducing

**Comment by StarGazer1258** [comment]
For future reference:
---
This bug seems to be caused by having songs that do not have a `hash` field in their info.json file. Songs downloaded by BeatDrop will have this field calculated and added automatically. Songs downloaded from other sources may not necessarily have this field and when viewed in BeatDrop, this bug will occur.

In the past, the code to calculate the hash fo songs when scanned has been faulty. This should be rectified with the merging of #36. 

**To fix this bug for yourself:**
1. Update to BeatDrop v2.4.0 or above.

1. Go to settings.

1. Click on "Scan for Songs."

1. Wait for the scanning to finish. Songs should now have the required `hash` field.
